defaults:
  - _self_
  - model/sam3
  - model/lotus
  - model/stablenormal

project:
  name: "Relative-3D"
  device: "cuda"
  seed: 2025

paths:
  # Changed from "./data/inputs" to match your request
  input_dir: "./input"
  output_dir: "./outputs/${now:%Y-%m-%d_%H-%M-%S}"

visualization:
  enable_viser: true
  port: 8080