defaults:
  - _self_
  - model/sam3
  - model/lotus
  - model/lotus_normal

project:
  name: "Relative-3D"
  device: "cuda"
  seed: 2025

# Disable Hydra's automatic directory creation
hydra:
  run:
    dir: .
  output_subdir: null

paths:
  input_dir: "./input"
  # New Structured Output Paths
  output_root: "./output"
  segmentation_dir: "${paths.output_root}/segmentation"
  depth_dir: "${paths.output_root}/depth"
  normals_dir: "${paths.output_root}/normals"
  cloud_dir: "${paths.output_root}/pointclouds"

visualization:
  enable_viser: true
  port: 8080